### ISSUE TITLE
ImportError (Python3.9, protobuf 21.5)

### ISSUE THREAD

**Issue by BarnabasSzabolcs** [google/cld3#72]
Installed `gcld3` using pip, and it worked until protobuf got updated in homebrew.
Now, `import gcld3` does not work.
Basically, gcld3's library tries to find `libprotobuf.30.dylib` but I have `libprotobuf.32.dylib` (and renaming it to libprotobuf.30.dylib does not work)
What would be a solution for this problem?

Error Message:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Volumes/MacintoshHDD/Programming/PycharmProjects/_venvs/rhymedict-crawlers/lib/python3.9/site-packages/gcld3/__init__.py", line 1, in <module>
    from .pybind_ext import *
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: dlopen(/Volumes/MacintoshHDD/Programming/PycharmProjects/_venvs/rhymedict-crawlers/lib/python3.9/site-packages/gcld3/pybind_ext.cpython-39-darwin.so, 2): Library not loaded: /usr/local/opt/protobuf/lib/libprotobuf.30.dylib
  Referenced from: /Volumes/MacintoshHDD/Programming/PycharmProjects/_venvs/rhymedict-crawlers/lib/python3.9/site-packages/gcld3/pybind_ext.cpython-39-darwin.so
  Reason: image not found
```

**Comment by vkmrishad** [comment]
I followed these steps specific to v3.19.4 to fix this issue.

https://gist.github.com/rajkrrsingh/77f3c4d20c109c96a3e9b36c224c6b3d
https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.4
